;;; company-coq-abbrev.el --- List of tactics, auto-generated from RefMan

;; Copyright (C) 2015  Clément Pit--Claudel
;; Author: Clément Pit--Claudel <clement.pitclaudel@live.com>
;; URL: https://github.com/cpitclaudel/company-coq

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;;; Code:

(defconst company-coq--refman-ltac-abbrevs
  (list
    '("abstract @{expr}" . ("9s" . 881))
    '("abstract @{expr} using @{ident}" . ("9s" . 885))
    '("appcontext @{ident} [@{cpattern}]" . ("9s" . 868))
    '("context @{ident} [@{cpattern}]" . ("9s" . 867))
    '("context @{ident} [@{expr}]" . ("9s" . 871))
    '("do @{num} @{expr}" . ("9s" . 840))
    '("eval @{redexpr} in @{term}" . ("9s" . 874))
    '("exactly_once @{expr}" . ("9s" . 848))
    '("fresh @{component+}" . ("9s" . 873))
    '("fun @{ident+} => @{expr}" . ("9s" . 864))
    '("guard @{test}" . ("9s" . 879))
    '("numgoals" . ("9s" . 878))
    '("once @{expr}" . ("9s" . 847))
    '("progress @{expr}" . ("9s" . 843))
    '("repeat @{expr}" . ("9s" . 841))
    '("solve [@{expr|+}]" . ("9s" . 850))
    '("time @{string} @{expr}" . ("9s" . 863))
    '("timeout @{num} @{expr}" . ("9s" . 862))
    '("try @{expr}" . ("9s" . 842))
    '("tryif @{expr} then @{expr} else @{expr}" . ("9s" . 846))
    '("type of @{term}" . ("9s" . 875))
    '("type_term @{term}" . ("9s" . 877))
    '("uconstr : @{term}" . ("9s" . 876))))

(defconst company-coq--refman-tactic-abbrevs
  (list
    '("discrR" . ("30" . 159))
    '("split_Rabs" . ("30" . 160))
    '("split_Rmult" . ("30" . 161))
    '("exact @{term}" . ("6p" . 370))
    '("eexact @{term}" . ("6p" . 372))
    '("assumption" . ("6q" . 373))
    '("eassumption" . ("6q" . 375))
    '("refine @{term}" . ("6r" . 376))
    '("simple refine @{term}" . ("6r" . 379))
    '("apply @{term}" . ("6s" . 380))
    '("apply @{term} with @{term+}" . ("6s" . 383))
    '("apply @{term} with (@{ref&} := @{term&})" . ("6s" . 385))
    '("apply @{term,+}" . ("6s" . 386))
    '("eapply @{term}" . ("6s" . 387))
    '("simple apply @{term}" . ("6s" . 388))
    '("lapply @{term}" . ("6s" . 389))
    '("apply @{term} in @{ident}" . ("6t" . 391))
    '("apply @{term,+} in @{ident}" . ("6t" . 394))
    '("apply @{term,&} with @{bindings_list,&} in @{ident}" . ("6t" . 395))
    '("eapply @{term,&} with @{bindings_list,&} in @{ident}" . ("6t" . 396))
    '("apply @{term,&} with @{bindings_list,&} in @{ident} as @{intro_pattern}" . ("6t" . 397))
    '("eapply @{term,&} with @{bindings_list,&} in @{ident} as @{intro_pattern}" . ("6t" . 398))
    '("simple apply @{term} in @{ident}" . ("6t" . 399))
    '("apply @{term,&} in @{ident} as @{intro_pattern}" . ("6t" . 400))
    '("simple apply @{term,&} in @{ident}" . ("6t" . 400))
    '("simple apply @{term,&} in @{ident} as @{intro_pattern}" . ("6t" . 400))
    '("simple apply @{term,&} with @{bindings_list,&} in @{ident}" . ("6t" . 400))
    '("simple apply @{term,&} with @{bindings_list,&} in @{ident} as @{intro_pattern}" . ("6t" . 400))
    '("constructor" . ("6u" . 404))
    '("split" . ("6u" . 407))
    '("left" . ("6u" . 412))
    '("right" . ("6u" . 413))
    '("econstructor" . ("6u" . 418))
    '("eexists" . ("6u" . 419))
    '("esplit" . ("6u" . 420))
    '("eleft" . ("6u" . 421))
    '("eright" . ("6u" . 422))
    '("constructor @{num}" . ("6u" . 401))
    '("constructor @{num} with @{bindings_list}" . ("6u" . 405))
    '("constructor @{tactic}" . ("6u" . 406))
    '("exists @{bindings_list}" . ("6u" . 409))
    '("exists @{bindings_list,+}" . ("6u" . 411))
    '("left with @{bindings_list}" . ("6u" . 415))
    '("right with @{bindings_list}" . ("6u" . 416))
    '("split with @{bindings_list}" . ("6u" . 417))
    '("intro" . ("6w" . 423))
    '("intros" . ("6w" . 426))
    '("intro at top" . ("6w" . 436))
    '("intro at bottom" . ("6w" . 437))
    '("intro @{ident}" . ("6w" . 427))
    '("intros @{ident+}" . ("6w" . 429))
    '("intros until @{ident}" . ("6w" . 430))
    '("intros until @{num}" . ("6w" . 432))
    '("intro after @{ident}" . ("6w" . 434))
    '("intro before @{ident}" . ("6w" . 435))
    '("intro @{ident} after @{ident}" . ("6w" . 439))
    '("intro @{ident} before @{ident}" . ("6w" . 440))
    '("intro @{ident} at top" . ("6w" . 441))
    '("intro @{ident} at bottom" . ("6w" . 442))
    '("intros @{intro_pattern+}" . ("6y" . 443))
    '("clear" . ("6z" . 452))
    '("clear @{ident}" . ("6z" . 444))
    '("clear @{ident+}" . ("6z" . 448))
    '("clearbody @{ident}" . ("6z" . 449))
    '("clear - @{ident+}" . ("6z" . 451))
    '("clear dependent @{ident}" . ("6z" . 453))
    '("revert @{ident+}" . ("70" . 454))
    '("revert dependent @{ident}" . ("70" . 457))
    '("move @{ident} after @{ident}" . ("71" . 458))
    '("move @{ident} before @{ident}" . ("71" . 459))
    '("move @{ident} at top" . ("71" . 460))
    '("move @{ident} at bottom" . ("71" . 461))
    '("rename @{ident} into @{ident}" . ("72" . 465))
    '("rename @{ident,&} into @{ident,&}" . ("72" . 466))
    '("set (@{ident} := @{term})" . ("73" . 469))
    '("set (@{ident} := @{term}) in @{goal_occurrences}" . ("73" . 471))
    '("set (@{ident} @{binder+} := @{term})" . ("73" . 472))
    '("set @{term}" . ("73" . 473))
    '("set (@{ident} @{binder+} := @{term}) in @{goal_occurrences}" . ("73" . 474))
    '("set @{term} in @{goal_occurrences}" . ("73" . 475))
    '("remember @{term} as @{ident}" . ("73" . 476))
    '("remember @{term} as @{ident} eqn:@{ident}" . ("73" . 477))
    '("remember @{term} as @{ident} in @{goal_occurrences}" . ("73" . 478))
    '("pose (@{ident} := @{term})" . ("73" . 479))
    '("pose (@{ident} @{binder+} := @{term})" . ("73" . 480))
    '("pose @{term}" . ("73" . 481))
    '("decompose [@{qualid+}] @{term}" . ("74" . 482))
    '("decompose sum @{term}" . ("74" . 483))
    '("decompose record @{term}" . ("74" . 484))
    '("assert (@{ident} : @{form})" . ("76" . 485))
    '("assert @{form}" . ("76" . 487))
    '("assert @{form} by @{tactic}" . ("76" . 488))
    '("assert @{form} as @{intro_pattern}" . ("76" . 490))
    '("assert @{form} as @{intro_pattern} by @{tactic}" . ("76" . 491))
    '("assert (@{ident} := @{term})" . ("76" . 492))
    '("pose proof @{term} as @{intro_pattern}" . ("76" . 494))
    '("enough (@{ident} : @{form})" . ("76" . 495))
    '("enough @{form}" . ("76" . 496))
    '("enough @{form} as @{intro_pattern}" . ("76" . 497))
    '("enough (@{ident} : @{form}) by @{tactic}" . ("76" . 498))
    '("enough @{form} by @{tactic}" . ("76" . 499))
    '("enough @{form} as @{intro_pattern} by @{tactic}" . ("76" . 500))
    '("cut @{form}" . ("76" . 501))
    '("specialize (@{ident} @{term+})" . ("76" . 502))
    '("specialize @{ident} with @{bindings_list}" . ("76" . 503))
    '("generalize @{term}" . ("78" . 506))
    '("generalize @{term,+}" . ("78" . 507))
    '("generalize @{term} at @{num+}" . ("78" . 508))
    '("generalize @{term} as @{ident}" . ("78" . 509))
    '("generalize @{term,&} at @{num+,&} as @{ident,&}" . ("78" . 510))
    '("generalize dependent @{term}" . ("78" . 511))
    '("evar (@{ident} : @{term})" . ("79" . 512))
    '("instantiate" . ("7a" . 517))
    '("instantiate (@{num} := @{term})" . ("7a" . 513))
    '("instantiate (@{num} := @{term}) in @{ident}" . ("7a" . 514))
    '("instantiate (@{num} := @{term}) in (Value of @{ident})" . ("7a" . 515))
    '("instantiate (@{num} := @{term}) in (Type of @{ident})" . ("7a" . 516))
    '("absurd @{term}" . ("7b" . 518))
    '("contradiction" . ("7c" . 519))
    '("contradiction @{ident}" . ("7c" . 521))
    '("contradict @{ident}" . ("7d" . 522))
    '("exfalso" . ("7e" . 523))
    '("destruct @{term}" . ("7g" . 524))
    '("destruct @{term,+}" . ("7g" . 525))
    '("destruct @{term} as @{disj_conj_intro_pattern}" . ("7g" . 526))
    '("destruct @{term} eqn:@{naming_intro_pattern}" . ("7g" . 527))
    '("destruct @{term} with @{bindings_list}" . ("7g" . 528))
    '("edestruct @{term}" . ("7g" . 529))
    '("destruct @{term} using @{term}" . ("7g" . 530))
    '("destruct @{term} using @{term} with @{bindings_list}" . ("7g" . 531))
    '("destruct @{term} in @{goal_occurrences}" . ("7g" . 532))
    '("destruct @{term} with @{bindings_list} as @{disj_conj_intro_pattern} eqn:@{naming_intro_pattern} using @{term} with @{bindings_list} in @{goal_occurrences}" . ("7g" . 533))
    '("edestruct @{term} with @{bindings_list} as @{disj_conj_intro_pattern} eqn:@{naming_intro_pattern} using @{term} with @{bindings_list} in @{goal_occurrences}" . ("7g" . 534))
    '("case @{term}" . ("7g" . 535))
    '("case @{term} with @{bindings_list}" . ("7g" . 536))
    '("ecase @{term}" . ("7g" . 537))
    '("ecase @{term} with @{bindings_list}" . ("7g" . 538))
    '("simple destruct @{ident}" . ("7g" . 539))
    '("simple destruct @{num}" . ("7g" . 540))
    '("case_eq @{term}" . ("7g" . 541))
    '("induction @{term}" . ("7h" . 542))
    '("induction @{term} as @{disj_conj_intro_pattern}" . ("7h" . 545))
    '("induction @{term} with @{bindings_list}" . ("7h" . 546))
    '("einduction @{term}" . ("7h" . 547))
    '("induction @{term} using @{term}" . ("7h" . 548))
    '("induction @{term} using @{term} with @{bindings_list}" . ("7h" . 549))
    '("induction @{term,+} using @{qualid}" . ("7h" . 550))
    '("induction @{term} in @{goal_occurrences}" . ("7h" . 551))
    '("induction @{term} with @{bindings_list} as @{disj_conj_intro_pattern} using @{term} with @{bindings_list} in @{goal_occurrences}" . ("7h" . 552))
    '("einduction @{term} with @{bindings_list} as @{disj_conj_intro_pattern} using @{term} with @{bindings_list} in @{goal_occurrences}" . ("7h" . 553))
    '("elim @{term}" . ("7h" . 554))
    '("elim @{term} with @{bindings_list}" . ("7h" . 555))
    '("eelim @{term}" . ("7h" . 556))
    '("elim @{term} using @{term}" . ("7h" . 557))
    '("elim @{term} using @{term} with @{bindings_list}" . ("7h" . 558))
    '("elim @{term} with @{bindings_list} using @{term} with @{bindings_list}" . ("7h" . 559))
    '("eelim @{term} with @{bindings_list} using @{term} with @{bindings_list}" . ("7h" . 560))
    '("elimtype @{form}" . ("7h" . 561))
    '("simple induction @{ident}" . ("7h" . 562))
    '("simple induction @{num}" . ("7h" . 563))
    '("double induction @{ident} @{ident}" . ("7i" . 564))
    '("double induction @{num} @{num}" . ("7i" . 565))
    '("dependent induction @{ident}" . ("7j" . 566))
    '("dependent induction @{ident} generalizing @{ident+}" . ("7j" . 567))
    '("dependent destruction @{ident}" . ("7j" . 568))
    '("functional induction (@{qualid} @{term+})" . ("7k" . 569))
    '("functional induction (@{qualid} @{term+}) as @{disj_conj_intro_pattern} using @{term} with @{bindings_list}" . ("7k" . 572))
    '("discriminate" . ("7l" . 580))
    '("discriminate @{term}" . ("7l" . 573))
    '("discriminate @{num}" . ("7l" . 576))
    '("discriminate @{term} with @{bindings_list}" . ("7l" . 577))
    '("ediscriminate @{num}" . ("7l" . 578))
    '("ediscriminate @{term}" . ("7l" . 579))
    '("ediscriminate @{term} with @{bindings_list}" . ("7l" . 579))
    '("injection" . ("7n" . 590))
    '("injection @{term}" . ("7n" . 582))
    '("injection @{num}" . ("7n" . 586))
    '("injection @{term} with @{bindings_list}" . ("7n" . 587))
    '("einjection @{num}" . ("7n" . 588))
    '("einjection @{term}" . ("7n" . 589))
    '("einjection @{term} with @{bindings_list}" . ("7n" . 589))
    '("injection @{term} as @{intro_pattern+}" . ("7n" . 592))
    '("injection @{term} with @{bindings_list} as @{intro_pattern+}" . ("7n" . 592))
    '("injection @{num} as @{intro_pattern+}" . ("7n" . 593))
    '("injection as @{intro_pattern+}" . ("7n" . 594))
    '("einjection @{term} as @{intro_pattern+}" . ("7n" . 595))
    '("einjection @{term} with @{bindings_list} as @{intro_pattern+}" . ("7n" . 595))
    '("einjection @{num} as @{intro_pattern+}" . ("7n" . 596))
    '("einjection as @{intro_pattern+}" . ("7n" . 597))
    '("inversion @{ident}" . ("7o" . 598))
    '("inversion @{num}" . ("7o" . 599))
    '("inversion_clear @{ident}" . ("7o" . 600))
    '("inversion @{ident} as @{intro_pattern}" . ("7o" . 601))
    '("inversion @{num} as @{intro_pattern}" . ("7o" . 602))
    '("inversion_clear @{ident} as @{intro_pattern}" . ("7o" . 603))
    '("inversion @{ident} in @{ident+}" . ("7o" . 604))
    '("inversion @{ident} as @{intro_pattern} in @{ident+}" . ("7o" . 605))
    '("inversion_clear @{ident} in @{ident+}" . ("7o" . 606))
    '("inversion_clear @{ident} as @{intro_pattern} in @{ident+}" . ("7o" . 607))
    '("dependent inversion @{ident}" . ("7o" . 608))
    '("dependent inversion @{ident} as @{intro_pattern}" . ("7o" . 609))
    '("dependent inversion_clear @{ident}" . ("7o" . 610))
    '("dependent inversion_clear @{ident} as @{intro_pattern}" . ("7o" . 611))
    '("dependent inversion @{ident} with @{term}" . ("7o" . 612))
    '("dependent inversion @{ident} as @{intro_pattern} with @{term}" . ("7o" . 613))
    '("dependent inversion_clear @{ident} with @{term}" . ("7o" . 615))
    '("dependent inversion_clear @{ident} as @{intro_pattern} with @{term}" . ("7o" . 616))
    '("simple inversion @{ident}" . ("7o" . 617))
    '("simple inversion @{ident} as @{intro_pattern}" . ("7o" . 618))
    '("inversion @{ident} using @{ident'}" . ("7o" . 619))
    '("inversion @{ident} using @{ident'} in @{ident+}" . ("7o" . 620))
    '("fix @{ident} @{num}" . ("7p" . 621))
    '("fix @{ident} @{num} with (@{ident&} @{binder+&} : @{type&})" . ("7p" . 622))
    '("fix @{ident} @{num} with (@{ident&} @{binder+&} {struct @{ident'&}} : @{type&})" . ("7p" . 622))
    '("cofix @{ident}" . ("7q" . 623))
    '("cofix @{ident} with (@{ident&} @{binder+&} : @{type&})" . ("7q" . 624))
    '("rewrite @{term}" . ("7s" . 625))
    '("rewrite -> @{term}" . ("7s" . 628))
    '("rewrite <- @{term}" . ("7s" . 629))
    '("rewrite @{term} in @{clause}" . ("7s" . 630))
    '("rewrite @{term} at @{occurrences}" . ("7s" . 631))
    '("rewrite @{term} by @{tactic}" . ("7s" . 632))
    '("rewrite @{term,+}" . ("7s" . 633))
    '("erewrite @{term}" . ("7s" . 634))
    '("replace @{term} with @{term}" . ("7t" . 635))
    '("replace @{term} with @{term} by @{tactic}" . ("7t" . 637))
    '("replace @{term}" . ("7t" . 638))
    '("replace -> @{term}" . ("7t" . 639))
    '("replace <- @{term}" . ("7t" . 640))
    '("replace @{term} with @{term} in @{clause}" . ("7t" . 641))
    '("replace @{term} with @{term} in @{clause} by @{tactic}" . ("7t" . 642))
    '("replace @{term} in @{clause}" . ("7t" . 643))
    '("replace -> @{term} in @{clause}" . ("7t" . 644))
    '("replace <- @{term} in @{clause}" . ("7t" . 645))
    '("cutrewrite <- (@{term} = @{term})" . ("7t" . 646))
    '("cutrewrite -> (@{term} = @{term})" . ("7t" . 647))
    '("subst @{ident}" . ("7u" . 648))
    '("subst @{ident+}" . ("7u" . 649))
    '("stepl @{term}" . ("7v" . 651))
    '("stepl @{term} by @{tactic}" . ("7v" . 652))
    '("stepr @{term}" . ("7v" . 653))
    '("stepr @{term} by @{tactic}" . ("7v" . 654))
    '("change @{term}" . ("7w" . 656))
    '("change @{term} with @{term}" . ("7w" . 658))
    '("change @{term} at @{num+} with @{term}" . ("7w" . 659))
    '("change @{term} in @{ident}" . ("7w" . 660))
    '("change @{term} with @{term} in @{ident}" . ("7w" . 661))
    '("change @{term} at @{num+} with @{term} in @{ident}" . ("7w" . 662))
    '("compute" . ("7y" . 665))
    '("cbv" . ("7y" . 667))
    '("lazy" . ("7y" . 668))
    '("vm_compute" . ("7y" . 675))
    '("native_compute" . ("7y" . 676))
    '("cbv @{flag+}" . ("7y" . 663))
    '("lazy @{flag+}" . ("7y" . 664))
    '("compute [@{qualid+}]" . ("7y" . 669))
    '("cbv [@{qualid+}]" . ("7y" . 670))
    '("compute -[@{qualid+}]" . ("7y" . 671))
    '("cbv -[@{qualid+}]" . ("7y" . 672))
    '("lazy [@{qualid+}]" . ("7y" . 673))
    '("lazy -[@{qualid+}]" . ("7y" . 674))
    '("red" . ("7z" . 677))
    '("hnf" . ("80" . 679))
    '("cbn" . ("81" . 680))
    '("simpl" . ("81" . 681))
    '("cbn [@{qualid+}]" . ("81" . 686))
    '("cbn -[@{qualid+}]" . ("81" . 687))
    '("simpl @{pattern}" . ("81" . 688))
    '("simpl @{pattern} at @{num+}" . ("81" . 689))
    '("simpl @{qualid}" . ("81" . 690))
    '("simpl @{string}" . ("81" . 691))
    '("simpl @{qualid} at @{num+}" . ("81" . 692))
    '("simpl @{string} at @{num+}" . ("81" . 693))
    '("unfold @{qualid}" . ("82" . 694))
    '("unfold @{qualid,+}" . ("82" . 696))
    '("unfold @{qualid,&} at @{num,+,&}" . ("82" . 697))
    '("unfold @{string}" . ("82" . 698))
    '("unfold @{string}%@{key}" . ("82" . 699))
    '("unfold @{qualid_or_string,&} at @{num,+,&}" . ("82" . 700))
    '("fold" . ("83" . 702))
    '("fold @{term}" . ("83" . 701))
    '("pattern" . ("84" . 708))
    '("pattern @{term}" . ("84" . 703))
    '("pattern @{term} at @{num+}" . ("84" . 704))
    '("pattern @{term} at - @{num+}" . ("84" . 705))
    '("pattern @{term,+}" . ("84" . 706))
    '("pattern @{term,&} at @{num+,&}" . ("84" . 707))
    '("auto" . ("87" . 710))
    '("auto with *" . ("87" . 713))
    '("trivial" . ("87" . 716))
    '("trivial with *" . ("87" . 718))
    '("auto @{num}" . ("87" . 711))
    '("auto with @{ident+}" . ("87" . 712))
    '("auto using @{lemma,+}" . ("87" . 714))
    '("auto using @{lemma,+} with @{ident+}" . ("87" . 715))
    '("trivial with @{ident+}" . ("87" . 717))
    '("eauto" . ("88" . 719))
    '("autounfold with *" . ("89" . 722))
    '("autounfold with @{ident+}" . ("89" . 720))
    '("autounfold with @{ident+} in @{clause}" . ("89" . 721))
    '("autorewrite with @{ident+}" . ("8a" . 723))
    '("autorewrite with @{ident+} using @{tactic}" . ("8a" . 724))
    '("autorewrite with @{ident+} in @{qualid}" . ("8a" . 725))
    '("autorewrite with @{ident+} in @{qualid} using @{tactic}" . ("8a" . 726))
    '("autorewrite with @{ident+} in @{clause}" . ("8a" . 727))
    '("tauto" . ("8l" . 767))
    '("intuition" . ("8m" . 769))
    '("intuition @{tactic}" . ("8m" . 768))
    '("rtauto" . ("8n" . 770))
    '("firstorder" . ("8o" . 771))
    '("firstorder @{tactic}" . ("8o" . 774))
    '("firstorder with @{ident+}" . ("8o" . 775))
    '("firstorder using @{qualid,+}" . ("8o" . 776))
    '("firstorder using @{qualid,+} with @{ident+}" . ("8o" . 777))
    '("congruence" . ("8p" . 779))
    '("congruence @{n}" . ("8p" . 780))
    '("congruence with @{term+}" . ("8p" . 781))
    '("constr_eq @{term} @{term}" . ("8r" . 784))
    '("unify @{term} @{term}" . ("8s" . 786))
    '("unify @{term} @{term} with @{ident}" . ("8s" . 788))
    '("is_evar @{term}" . ("8t" . 789))
    '("has_evar @{term}" . ("8u" . 791))
    '("is_var @{term}" . ("8v" . 793))
    '("f_equal" . ("8x" . 795))
    '("reflexivity" . ("8y" . 796))
    '("symmetry" . ("8z" . 799))
    '("symmetry in @{ident}" . ("8z" . 800))
    '("transitivity @{term}" . ("90" . 801))
    '("decide equality" . ("92" . 802))
    '("compare @{term} @{term}" . ("93" . 803))
    '("simplify_eq" . ("94" . 806))
    '("simplify_eq @{term}" . ("94" . 804))
    '("simplify_eq @{num}" . ("94" . 805))
    '("esimplify_eq @{num}" . ("94" . 807))
    '("esimplify_eq @{term}" . ("94" . 808))
    '("esimplify_eq @{term} with @{bindings_list}" . ("94" . 808))
    '("dependent rewrite -> @{ident}" . ("95" . 810))
    '("dependent rewrite <- @{ident}" . ("95" . 811))
    '("functional inversion @{ident}" . ("97" . 812))
    '("functional inversion @{num}" . ("97" . 815))
    '("functional inversion @{ident} @{qualid}" . ("97" . 816))
    '("quote @{ident}" . ("98" . 817))
    '("quote @{ident} [@{ident+}]" . ("98" . 819))
    '("classical_left" . ("9a" . 820))
    '("classical_right" . ("9a" . 821))
    '("btauto" . ("9c" . 822))
    '("omega" . ("9d" . 823))
    '("ring" . ("9e" . 824))
    '("ring_simplify @{term+}" . ("9e" . 825))
    '("field" . ("9f" . 827))
    '("field_simplify_eq" . ("9f" . 829))
    '("field_simplify @{term+}" . ("9f" . 828))
    '("fourier" . ("9g" . 831))
    '("cycle @{num}" . ("9i" . 832))
    '("swap @{num} @{num}" . ("9j" . 833))
    '("revgoals" . ("9k" . 834))
    '("shelve" . ("9l" . 835))
    '("shelve_unifiable" . ("9l" . 836))
    '("give_up" . ("9n" . 838))
    '("admit" . ("9n" . 839))
    '("idtac" . ("9s" . 852))
    '("fail" . ("9s" . 854))
    '("gfail" . ("9s" . 858))
    '("idtac @{message_token+}" . ("9s" . 853))
    '("fail @{n}" . ("9s" . 855))
    '("fail @{message_token+}" . ("9s" . 856))
    '("fail @{n} @{message_token+}" . ("9s" . 857))
    '("gfail @{message_token+}" . ("9s" . 859))
    '("gfail @{n} @{message_token+}" . ("9s" . 860))
    '("specialize_eqs" . ("a1" . 893))
    '("quote @{ident} in @{term} using @{tactic}" . ("a5" . 895))
    '("quote @{ident} [@{ident+}] in @{term} using @{tactic}" . ("a5" . 896))
    '("psatz" . ("eu" . 1005))
    '("lra" . ("ex" . 1006))
    '("lia" . ("f1" . 1007))
    '("nia" . ("f4" . 1008))
    '("ring_simplify" . ("fw" . 1055))
    '("ring [@{term+}]" . ("fw" . 1056))
    '("ring_simplify [@{term+}] @{t+} in @{ident}" . ("fw" . 1057))
    '("field_simplify" . ("fz" . 1068))
    '("field [@{term+}]" . ("fz" . 1067))
    '("field_simplify [@{term+}]" . ("fz" . 1069))
    '("field_simplify [@{term+}] @{term+}" . ("fz" . 1070))
    '("field_simplify in @{hyp}" . ("fz" . 1071))
    '("field_simplify [@{term+}] in @{hyp}" . ("fz" . 1072))
    '("field_simplify [@{term+}] @{term+} in @{hyp}" . ("fz" . 1073))
    '("field_simplify_eq [@{term+}]" . ("fz" . 1075))
    '("field_simplify_eq in @{hyp}" . ("fz" . 1076))
    '("field_simplify_eq [@{term+}] in @{hyp}" . ("fz" . 1077))
    '("nsatz" . ("g5" . 1079))
    '("nsatz with radicalmax:=@{num}%N strategy:=@{num}%Z parameters:=@{list of vars} variables:=@{list of vars}" . ("g5" . 1080))
    '("setoid_reflexivity" . ("gh" . 1081))
    '("setoid_symmetry" . ("gh" . 1082))
    '("setoid_transitivity" . ("gh" . 1083))
    '("setoid_symmetry in @{ident}" . ("gh" . 1082))
    '("setoid_rewrite @{term}" . ("gh" . 1084))
    '("setoid_rewrite @{term} in @{ident}" . ("gh" . 1084))
    '("setoid_rewrite <- @{term}" . ("gh" . 1085))
    '("setoid_rewrite <- @{term} in @{ident}" . ("gh" . 1085))
    '("setoid_rewrite <- @{term} at @{occs}" . ("gh" . 1086))
    '("setoid_rewrite <- @{term} at @{occs} in @{ident}" . ("gh" . 1086))
    '("setoid_rewrite @{term} at @{occs}" . ("gh" . 1087))
    '("setoid_rewrite @{term} at @{occs} in @{ident}" . ("gh" . 1087))
    '("setoid_rewrite @{orientation} @{term}" . ("gh" . 1087))
    '("setoid_rewrite @{orientation} @{term} in @{ident}" . ("gh" . 1087))
    '("setoid_rewrite @{orientation} @{term} at @{occs}" . ("gh" . 1087))
    '("setoid_rewrite @{orientation} @{term} at @{occs} in @{ident}" . ("gh" . 1087))
    '("setoid_replace @{term} with @{term}" . ("gh" . 1088))
    '("setoid_replace @{term} with @{term} by @{tactic}" . ("gh" . 1089))
    '("setoid_replace @{term} with @{term} using relation @{term}" . ("gh" . 1089))
    '("setoid_replace @{term} with @{term} using relation @{term} by @{tactic}" . ("gh" . 1089))
    '("setoid_replace @{term} with @{term} in @{ident}" . ("gh" . 1089))
    '("setoid_replace @{term} with @{term} in @{ident} by @{tactic}" . ("gh" . 1089))
    '("setoid_replace @{term} with @{term} in @{ident} using relation @{term}" . ("gh" . 1089))
    '("setoid_replace @{term} with @{term} in @{ident} using relation @{term} by @{tactic}" . ("gh" . 1089))
    '("rewrite_strat @{s}" . ("gq" . 1092))
    '("rewrite_strat @{s} in @{ident}" . ("gq" . 1092))))

(defconst company-coq--refman-vernac-abbrevs
  (list
    '("Abort." . ("5x" . 330))
    '("Abort @{ident}." . ("5x" . 332))
    '("Abort All." . ("5x" . 333))
    '("About @{qualid}." . ("3p" . 166))
    '("Add Field @{name} : @{field} (@{mod,+})." . ("g0" . 1078))
    '("Add LoadPath \"@{string}\"." . ("4l" . 252))
    '("Add LoadPath \"@{string}\" as @{dirpath}." . ("4l" . 251))
    '("Add ML Path \"@{string}\"." . ("4p" . 258))
    '("Add Printing Coercion @{qualid}." . ("dr" . 981))
    '("Add Printing Constructor @{ident}." . ("16" . 41))
    '("Add Printing If @{ident}." . ("1c" . 60))
    '("Add Printing Let @{ident}." . ("1c" . 56))
    '("Add Printing Record @{ident}." . ("16" . 40))
    '("Add Rec LoadPath \"@{string}\"." . ("4m" . 254))
    '("Add Rec LoadPath \"@{string}\" as @{dirpath}." . ("4m" . 253))
    '("Add Rec ML Path \"@{string}\"." . ("4q" . 259))
    '("Add Ring @{name} : @{ring} (@{mod,+})." . ("fx" . 1062))
    '("Add Search Blacklist \"@{string}\"." . ("49" . 220))
    '("Admit Obligations." . ("fo" . 1049))
    '("Admit Obligations of @{ident}." . ("fo" . 1049))
    '("Admitted." . ("5u" . 313))
    '("Arguments @{qualid} @{possibly_bracketed_ident+}." . ("1p" . 74))
    '("Arguments @{ident} !@{arg+}." . ("81" . 684))
    '("Arguments @{ident} @{possibly_bracketed_ident+} / @{possibly_bracketed_ident+}." . ("81" . 683))
    '("Arguments @{qualid} @{name&} %@{scope&}." . ("bj" . 911))
    '("Arguments @{qualid} : clear implicits." . ("1p" . 75))
    '("Arguments @{qualid} : clear scopes." . ("bj" . 912))
    '("Arguments @{qualid} : default implicits." . ("1q" . 78))
    '("Arguments @{qualid} @{name+} : rename." . ("1x" . 93))
    '("Arguments @{ident} @{possibly_bracketed_ident+} : simpl never." . ("81" . 682))
    '("Arguments @{ident} @{possibly_bracketed_ident+} : simpl nomatch." . ("81" . 685))
    '("Axiom @{ident} : @{term}." . ("10" . 2))
    '("Back." . ("4w" . 265))
    '("Back @{n}." . ("4w" . 266))
    '("BackTo @{num}." . ("4x" . 268))
    '("Backtrack @{num} @{num} @{num}." . ("4x" . 269))
    '("Bind Scope @{scope} with @{qualid}." . ("bj" . 915))
    '("Canonical Structure @{qualid}." . ("22" . 101))
    '("Canonical Structure @{ident}." . ("22" . 105))
    '("Canonical Structure @{ident} := @{term}." . ("22" . 103))
    '("Canonical Structure @{ident} := @{term} : @{type}." . ("22" . 102))
    '("Canonical Structure @{ident} : @{type} := @{term}." . ("22" . 104))
    '("Cd." . ("4k" . 250))
    '("Cd \"@{string}\"." . ("4k" . 249))
    '("Check @{term}." . ("41" . 187))
    '("@{selector}: Check @{term}." . ("41" . 188))
    '("Class @{ident} @{binder+} : @{sort}:= {@{field;+}}." . ("ea" . 982))
    '("Class @{ident} @{binder+} : @{sort}:= @{ident} : @{type}." . ("ea" . 983))
    '("Close Scope @{scope}." . ("bi" . 904))
    '("Coercion @{qualid} : @{class} >-> @{class}." . ("25" . 113))
    '("Coercion @{ident} := @{term}." . ("di" . 967))
    '("Coercion @{ident} := @{term} : @{type}." . ("di" . 968))
    '("Collection @{ident}:= @{ident+}." . ("5w" . 329))
    '("Combined Scheme @{ident} from @{ident}, .., @{ident}." . ("bu" . 949))
    '("Compute @{term}." . ("43" . 190))
    '("Conjecture @{ident} : @{term}." . ("10" . 7))
    '("Constraint @{ident} @{ord} @{ident}." . ("h6" . 1098))
    '("Context @{binder+}." . ("ed" . 992))
    '("Corollary @{ident} : @{type}." . ("14" . 32))
    '("Corollary @{ident} @{binders} : @{type}." . ("14" . 32))
    '("Create HintDb @{ident}." . ("8d" . 728))
    '("Create HintDb @{ident} discriminated." . ("8d" . 728))
    '("Declare Implicit Tactic @{tactic}." . ("8j" . 768))
    '("Declare Instance." . ("eb" . 989))
    '("Declare ML Module \"@{string}\" .. \"@{string}\"." . ("4g" . 243))
    '("Declare Module @{ident} : @{module_type}." . ("2c" . 162))
    '("Declare Module @{ident} @{module_bindings} : @{module_type}." . ("2c" . 163))
    '("Declare Reduction @{ident} := @{convtactic}." . ("5n" . 297))
    '("Declare Right Step @{term}." . ("7v" . 655))
    '("Defined." . ("5t" . 304))
    '("Definition." . ("11" . 13))
    '("Definition @{ident} := @{term}." . ("11" . 11))
    '("Definition @{ident} : @{type}." . ("14" . 34))
    '("Definition @{ident} @{binders} : @{type}." . ("14" . 34))
    '("Delimit Scope @{scope} with @{ident}." . ("bj" . 909))
    '("Derive Dependent Inversion_clear @{ident} with forall @{ident&}: @{type&}, @{I} @{arg+} Sort @{sort}." . ("bw" . 954))
    '("Derive Dependent Inversion @{ident} with forall @{ident&}: @{type&}, @{I} @{arg+} Sort @{sort}." . ("bw" . 953))
    '("Derive Inversion_clear @{ident} with forall @{ident&}: @{type&}, @{I} @{arg+} Sort @{sort}." . ("bw" . 952))
    '("Derive Inversion @{ident} with forall @{ident&}: @{type&}, @{I} @{arg+} Sort @{sort}." . ("bw" . 951))
    '("Derive @{ident} SuchThat @{term} As @{ident}." . ("hb" . 1102))
    '("Drop." . ("50" . 272))
    '("End @{ident}." . ("1g" . 71))
    '("Eval @{convtactic} in @{term}." . ("42" . 189))
    '("Example @{ident} := @{term}." . ("11" . 16))
    '("Existential @{num} := @{term}." . ("5y" . 334))
    '("Existing Class @{ident}." . ("ea" . 984))
    '("Existing Instance @{ident}." . ("ec" . 990))
    '("Existing Instance @{ident} @{priority}." . ("ec" . 990))
    '("Existing Instances @{ident+}." . ("ec" . 991))
    '("Existing Instances @{ident+} @{priority}." . ("ec" . 991))
    '("Export @{qualid}." . ("2c" . 165))
    '("Extract Constant @{qualid} => \"@{string}\"." . ("fb" . 1027))
    '("Extract Constant @{qualid} \"@{string+}\" => \"@{string}\"." . ("fb" . 1029))
    '("Extract Inductive @{qualid} => \"@{string}\" [\"@{string+}\"] @{optstring}." . ("fb" . 1030))
    '("Extract Inlined Constant @{qualid} => \"@{string}\"." . ("fb" . 1028))
    '("Extraction @{term}." . ("44" . 191))
    '("Extraction @{qualid}." . ("f6" . 1009))
    '("Extraction \"@{file}\" @{qualid+}." . ("f6" . 1011))
    '("Extraction Blacklist @{ident+}." . ("fc" . 1031))
    '("Extraction Implicit @{qualid} [@{ident+}]." . ("fa" . 1025))
    '("Extraction Language Haskell." . ("f8" . 1016))
    '("Extraction Language Ocaml." . ("f8" . 1015))
    '("Extraction Language Scheme." . ("f8" . 1017))
    '("Extraction Library @{ident}." . ("f6" . 1012))
    '("Fact @{ident} : @{type}." . ("14" . 31))
    '("Fact @{ident} @{binders} : @{type}." . ("14" . 31))
    '("Fixpoint @{ident} @{params} {struct @{ident}} : type := @{term}." . ("13" . 24))
    '("Focus." . ("63" . 340))
    '("Focus @{num}." . ("63" . 341))
    '("From @{dirpath} Require @{qualid}." . ("4e" . 235))
    '("Functional Scheme @{ident} := Induction for @{ident'} Sort @{sort}." . ("bv" . 950))
    '("Generalizable All Variables." . ("24" . 108))
    '("Generalizable No Variables." . ("24" . 109))
    '("Generalizable Variable @{ident}." . ("24" . 110))
    '("Generalizable Variables @{ident+}." . ("24" . 111))
    '("Global." . ("5p" . 299))
    '("Global Arguments @{qualid} @{possibly_bracketed_ident+}." . ("1p" . 76))
    '("Global Arguments @{qualid} @{name&} %@{scope&}." . ("bj" . 913))
    '("Global Arguments @{qualid} : default implicits." . ("1q" . 79))
    '("Global Close Scope @{scope}." . ("bi" . 908))
    '("Global Generalizable All Variables." . ("24" . 112))
    '("Global Instance." . ("eb" . 987))
    '("Global Obligation Tactic := @{expr}." . ("fo" . 1042))
    '("Global Opaque @{qualid+}." . ("5j" . 290))
    '("Global Open Scope @{scope}." . ("bi" . 907))
    '("Global Set @{flag}." . ("3s" . 172))
    '("Global Set @{option} @{value}." . ("3v" . 179))
    '("Global Unset @{flag}." . ("3t" . 175))
    '("Global Unset @{option}." . ("3w" . 182))
    '("Goal @{form}." . ("5s" . 301))
    '("Grab Existential Variables." . ("5z" . 335))
    '("Guarded." . ("6a" . 359))
    '("Hint @{hint_definition}." . ("8d" . 730))
    '("Hint @{hint_definition} : @{ident+}." . ("8d" . 729))
    '("Hint Constructors @{ident}." . ("8d" . 739))
    '("Hint Constructors @{ident+}." . ("8d" . 741))
    '("Hint Constructors @{ident} : @{ident+}." . ("8d" . 739))
    '("Hint Constructors @{ident+} : @{ident+}." . ("8d" . 741))
    '("Hint Extern @{num} => @{tactic}." . ("8d" . 746))
    '("Hint Extern @{num} => @{tactic} : @{ident+}." . ("8d" . 746))
    '("Hint Extern @{num} @{pattern} => @{tactic}." . ("8d" . 746))
    '("Hint Extern @{num} @{pattern} => @{tactic} : @{ident+}." . ("8d" . 746))
    '("Hint Immediate @{term}." . ("8d" . 736))
    '("Hint Immediate @{term+}." . ("8d" . 738))
    '("Hint Immediate @{term} : @{ident+}." . ("8d" . 736))
    '("Hint Immediate @{term+} : @{ident+}." . ("8d" . 738))
    '("Hint Local @{hint_definition}." . ("8d" . 749))
    '("Hint Local @{hint_definition} : @{ident+}." . ("8d" . 748))
    '("Hint Resolve @{term}." . ("8d" . 733))
    '("Hint Resolve @{term+}." . ("8d" . 735))
    '("Hint Resolve @{term} : @{ident+}." . ("8d" . 733))
    '("Hint Resolve @{term+} : @{ident+}." . ("8d" . 735))
    '("Hint Rewrite @{term+} : @{ident+}." . ("8h" . 755))
    '("Hint Rewrite -> @{term+} : @{ident+}." . ("8h" . 756))
    '("Hint Rewrite <- @{term+} : @{ident+}." . ("8h" . 757))
    '("Hint Rewrite @{term+} using @{tactic} : @{ident+}." . ("8h" . 758))
    '("Hint Unfold @{qualid}." . ("8d" . 742))
    '("Hint Unfold @{ident+}." . ("8d" . 743))
    '("Hint Unfold @{qualid} : @{ident+}." . ("8d" . 742))
    '("Hint Unfold @{ident+} : @{ident+}." . ("8d" . 743))
    '("Identity Coercion @{ident}:@{class} >-> @{class}." . ("dj" . 970))
    '("Implicit Type @{ident} : @{type}." . ("23" . 107))
    '("Implicit Types @{ident+} : @{type}." . ("23" . 106))
    '("Import @{qualid}." . ("2c" . 164))
    '("Include @{module}." . ("2c" . 139))
    '("Include @{module<++}." . ("2c" . 140))
    '("Infix \"@{symbol}\" := @{qualid} (@{modifier,+})." . ("b8" . 899))
    '("Info @{num} @{expr}." . ("9x" . 888))
    '("@{assumption_keyword} Inline @{assums}." . ("2c" . 156))
    '("Inspect @{num}." . ("3q" . 168))
    '("Instance @{ident} @{binder+} : Class @{term+} := {@{field;&} := @{b;&}}." . ("eb" . 985))
    '("Instance @{ident} @{binder+} : Class @{term+} @{priority} := {@{field;&} := @{b;&}}." . ("eb" . 985))
    '("Instance @{ident} @{binder+} : forall @{binder+}, Class @{term+} := @{term}." . ("eb" . 986))
    '("Instance @{ident} @{binder+} : forall @{binder+}, Class @{term+} @{priority} := @{term}." . ("eb" . 986))
    '("Lemma @{ident} : @{type}." . ("14" . 29))
    '("Lemma @{ident} @{binders} : @{type}." . ("14" . 29))
    '("Let @{ident} := @{term}." . ("11" . 18))
    '("Let @{ident} : @{term} := @{term}." . ("11" . 20))
    '("Let @{ident} : @{type}." . ("14" . 35))
    '("Let @{ident} @{binders} : @{type}." . ("14" . 35))
    '("Let CoFixpoint @{ident} @{cofix_bodywith+}." . ("11" . 22))
    '("Let Fixpoint @{ident} @{fix_bodywith+}." . ("11" . 21))
    '("Load @{ident}." . ("4c" . 226))
    '("Load \"@{string}\"." . ("4c" . 227))
    '("Load Verbose @{ident}." . ("4c" . 228))
    '("Load Verbose \"@{string}\"." . ("4c" . 229))
    '("Local." . ("5p" . 298))
    '("Local Arguments @{qualid} @{possibly_bracketed_ident+}." . ("1p" . 77))
    '("Local Arguments @{qualid} @{name&} %@{scope&}." . ("bj" . 914))
    '("Local Arguments @{qualid} : default implicits." . ("1q" . 80))
    '("Local Axiom @{ident} : @{term}." . ("10" . 6))
    '("Local Close Scope @{scope}." . ("bi" . 906))
    '("Local Coercion @{ident} := @{term}." . ("di" . 969))
    '("Local Coercion @{qualid} : @{class} >-> @{class}." . ("di" . 966))
    '("Local Declare ML Module \"@{string}\" .. \"@{string}\"." . ("4g" . 244))
    '("Local Definition @{ident} := @{term}." . ("11" . 15))
    '("Local Hint @{hint_definition}." . ("8d" . 732))
    '("Local Hint @{hint_definition} : @{ident+}." . ("8d" . 731))
    '("Local Hint Constructors @{ident}." . ("8d" . 739))
    '("Local Hint Constructors @{ident+}." . ("8d" . 741))
    '("Local Hint Constructors @{ident} : @{ident+}." . ("8d" . 739))
    '("Local Hint Constructors @{ident+} : @{ident+}." . ("8d" . 741))
    '("Local Hint Extern @{num} => @{tactic}." . ("8d" . 746))
    '("Local Hint Extern @{num} => @{tactic} : @{ident+}." . ("8d" . 746))
    '("Local Hint Extern @{num} @{pattern} => @{tactic}." . ("8d" . 746))
    '("Local Hint Extern @{num} @{pattern} => @{tactic} : @{ident+}." . ("8d" . 746))
    '("Local Hint Immediate @{term}." . ("8d" . 736))
    '("Local Hint Immediate @{term+}." . ("8d" . 738))
    '("Local Hint Immediate @{term} : @{ident+}." . ("8d" . 736))
    '("Local Hint Immediate @{term+} : @{ident+}." . ("8d" . 738))
    '("Local Hint Resolve @{term}." . ("8d" . 733))
    '("Local Hint Resolve @{term+}." . ("8d" . 735))
    '("Local Hint Resolve @{term} : @{ident+}." . ("8d" . 733))
    '("Local Hint Resolve @{term+} : @{ident+}." . ("8d" . 735))
    '("Local Hint Unfold @{qualid}." . ("8d" . 742))
    '("Local Hint Unfold @{ident+}." . ("8d" . 743))
    '("Local Hint Unfold @{qualid} : @{ident+}." . ("8d" . 742))
    '("Local Hint Unfold @{ident+} : @{ident+}." . ("8d" . 743))
    '("Local Identity Coercion @{ident}:@{ident} >-> @{ident}." . ("dj" . 972))
    '("Local Notation @{ident} := @{term}." . ("bn" . 935))
    '("Local Notation @{ident} @{ident&} @{ident&} := @{term}." . ("bn" . 935))
    '("Local Notation @{ident} := @{term} (only parsing)." . ("bn" . 935))
    '("Local Notation @{ident} @{ident&} @{ident&} := @{term} (only parsing)." . ("bn" . 935))
    '("Local Obligation Tactic := @{expr}." . ("fo" . 1041))
    '("Local Open Scope @{scope}." . ("bi" . 905))
    '("Local Set @{flag}." . ("3s" . 171))
    '("Local Set @{option} @{value}." . ("3v" . 178))
    '("Local SubClass @{ident} := @{type}." . ("dj" . 974))
    '("Local Unset @{flag}." . ("3t" . 174))
    '("Local Unset @{option}." . ("3w" . 181))
    '("Locate @{qualid}." . ("4a" . 222))
    '("Locate \"@{symbol}\"." . ("bc" . 902))
    '("Locate File \"@{string}\"." . ("4s" . 261))
    '("Locate Library @{dirpath}." . ("4t" . 262))
    '("Locate Ltac @{qualid}." . ("4a" . 225))
    '("Locate Module @{qualid}." . ("2c" . 169))
    '("Locate Term @{qualid}." . ("4a" . 223))
    '("Module @{ident}." . ("2c" . 123))
    '("Module @{ident} @{module_bindings}." . ("2c" . 134))
    '("Module @{ident} : @{module_type}." . ("2c" . 135))
    '("Module @{ident} <: @{module_type<:+}." . ("2c" . 137))
    '("Module @{ident} := @{module_expression}." . ("2c" . 147))
    '("Module @{ident} @{module_bindings} : @{module_type}." . ("2c" . 136))
    '("Module @{ident} @{module_bindings} <: @{module_type<:+}." . ("2c" . 138))
    '("Module @{ident} @{module_bindings} := @{module_expression}." . ("2c" . 148))
    '("Module @{ident} @{module_bindings} := @{module_expression<++}." . ("2c" . 151))
    '("Module @{ident} @{module_bindings} : @{module_type} := @{module_expression}." . ("2c" . 149))
    '("Module @{ident} @{module_bindings} <: @{module_type<:+}:= @{module_expression}." . ("2c" . 150))
    '("Module Type @{ident}." . ("2c" . 152))
    '("Module Type @{ident} @{module_bindings}." . ("2c" . 153))
    '("Module Type @{ident} := @{module_type}." . ("2c" . 159))
    '("Module Type @{ident} @{module_bindings} := @{module_type}." . ("2c" . 160))
    '("Module Type @{ident} @{module_bindings} := @{module_type<++}." . ("2c" . 161))
    '("Next Obligation." . ("fo" . 1046))
    '("Next Obligation of @{ident}." . ("fo" . 1046))
    '("Notation @{ident} := @{term}." . ("bn" . 935))
    '("Notation @{ident} @{ident&} @{ident&} := @{term}." . ("bn" . 935))
    '("Notation @{ident} := @{term} (only parsing)." . ("bn" . 935))
    '("Notation @{ident} @{ident&} @{ident&} := @{term} (only parsing)." . ("bn" . 935))
    '("Obligation num." . ("fo" . 1045))
    '("Obligation num of @{ident}." . ("fo" . 1045))
    '("Obligations." . ("fo" . 1044))
    '("Obligations of @{ident}." . ("fo" . 1044))
    '("Opaque @{qualid+}." . ("5j" . 289))
    '("Open Scope @{scope}." . ("bi" . 903))
    '("Optimize Heap." . ("6h" . 365))
    '("Optimize Proof." . ("6g" . 364))
    '("Parameter @{ident} : @{term}." . ("10" . 4))
    '("Parameter @{ident+} : @{term}." . ("10" . 5))
    '("Preterm." . ("fo" . 1050))
    '("Preterm of @{ident}." . ("fo" . 1050))
    '("Print @{qualid}." . ("3p" . 163))
    '("Print All." . ("3q" . 167))
    '("Print All Dependencies @{qualid}." . ("45" . 196))
    '("Print Assumptions @{qualid}." . ("45" . 193))
    '("Print Classes." . ("dl" . 975))
    '("Print Coercion Paths @{class} @{class}." . ("do" . 978))
    '("Print Coercions." . ("dm" . 976))
    '("Print Extraction Blacklist." . ("fc" . 1032))
    '("Print Extraction Inline." . ("f9" . 1023))
    '("Print Fields." . ("9f" . 830))
    '("Print Firstorder Solver." . ("8o" . 773))
    '("Print Grammar constr." . ("b6" . 897))
    '("Print Grammar pattern." . ("b6" . 898))
    '("Print Grammar tactic." . ("bo" . 937))
    '("Print Graph." . ("dn" . 977))
    '("Print Hint." . ("8g" . 751))
    '("Print Hint *." . ("8g" . 753))
    '("Print Hint @{ident}." . ("8g" . 752))
    '("Print HintDb @{ident}." . ("8g" . 754))
    '("Print Implicit @{qualid}." . ("1y" . 94))
    '("Print Instances @{typeclass}." . ("gi" . 1091))
    '("Print Libraries." . ("4f" . 242))
    '("Print LoadPath." . ("4o" . 256))
    '("Print LoadPath @{dirpath}." . ("4o" . 257))
    '("Print Ltac @{qualid}." . ("9v" . 887))
    '("Print ML Modules." . ("4h" . 247))
    '("Print ML Path \"@{string}\"." . ("4r" . 260))
    '("Print Module @{ident}." . ("2c" . 167))
    '("Print Module Type @{ident}." . ("2c" . 168))
    '("Print Opaque Dependencies @{qualid}." . ("45" . 194))
    '("Print Options." . ("3z" . 185))
    '("Print Rewrite HintDb @{ident}." . ("8h" . 759))
    '("Print Rings." . ("9e" . 826))
    '("Print Scope @{scope}." . ("bl" . 930))
    '("Print Scopes." . ("bl" . 929))
    '("Print Section @{ident}." . ("3q" . 169))
    '("Print Sorted Universes." . ("27" . 118))
    '("Print Sorted Universes \"@{string}\"." . ("27" . 119))
    '("Print Strategies." . ("5m" . 296))
    '("Print Strategy @{qualid}." . ("5m" . 295))
    '("Print Table @{table}." . ("3y" . 184))
    '("Print Table Printing If." . ("1c" . 63))
    '("Print Table Printing Let." . ("1c" . 59))
    '("Print Tables." . ("3z" . 186))
    '("Print Term @{qualid}." . ("3p" . 165))
    '("Print Transparent Dependencies @{qualid}." . ("45" . 195))
    '("Print Universes." . ("27" . 118))
    '("Print Universes \"@{string}\"." . ("27" . 119))
    '("Print Visibility." . ("bm" . 934))
    '("Print Visibility @{scope}." . ("bm" . 935))
    '("Program Definition @{ident} := @{term}." . ("fl" . 1034))
    '("Program Definition @{ident} : @{term} := @{term}." . ("fl" . 1036))
    '("Program Definition @{ident} @{binder+} : @{term} := @{term}." . ("fl" . 1037))
    '("Program Fixpoint @{ident} @{params} {order} : type := @{term}." . ("fm" . 1039))
    '("Program Instance." . ("eb" . 988))
    '("Program Lemma @{ident} : type." . ("fn" . 1040))
    '("Proof." . ("5v" . 315))
    '("Proof @{term}." . ("5v" . 314))
    '("Proof using." . ("5w" . 320))
    '("Proof using @{ident+}." . ("5w" . 316))
    '("Proof using -(@{ident+})." . ("5w" . 322))
    '("Proof using @{collection} *." . ("5w" . 326))
    '("Proof using @{collection} + @{collection}." . ("5w" . 323))
    '("Proof using @{collection} - @{collection}." . ("5w" . 324))
    '("Proof using @{collection} - (@{ident+})." . ("5w" . 325))
    '("Proof using All." . ("5w" . 318))
    '("Proof using Type." . ("5w" . 319))
    '("Proof using Type*." . ("5w" . 321))
    '("Proof using @{ident+} with @{tactic}." . ("5w" . 317))
    '("Proof with @{tactic}." . ("8j" . 765))
    '("Proof with @{tactic} using @{ident+}." . ("8j" . 766))
    '("Proposition @{ident} : @{type}." . ("14" . 33))
    '("Proposition @{ident} @{binders} : @{type}." . ("14" . 33))
    '("Pwd." . ("4j" . 248))
    '("Qed." . ("5t" . 302))
    '("Qed exporting." . ("9s" . 882))
    '("Qed exporting @{ident,+}." . ("9s" . 883))
    '("Quit." . ("4z" . 271))
    '("Recursive Extraction @{qualid+}." . ("44" . 192))
    '("Recursive Extraction Library @{ident}." . ("f6" . 1013))
    '("Redirect \"@{file}\" @{command}." . ("52" . 274))
    '("Remark @{ident} : @{type}." . ("14" . 30))
    '("Remark @{ident} @{binders} : @{type}." . ("14" . 30))
    '("Remove Hints @{term+} : @{ident+}." . ("8f" . 750))
    '("Remove LoadPath \"@{string}\"." . ("4n" . 255))
    '("Remove Printing If @{ident}." . ("1c" . 61))
    '("Remove Printing Let @{ident}." . ("1c" . 57))
    '("Remove Search Blacklist \"@{string}\"." . ("49" . 221))
    '("Require @{qualid}." . ("4e" . 231))
    '("Require @{qualid+}." . ("4e" . 234))
    '("Require Export @{qualid}." . ("4e" . 233))
    '("Require Import @{qualid}." . ("4e" . 232))
    '("Reset @{ident}." . ("4v" . 263))
    '("Reset Extraction Blacklist." . ("fc" . 1033))
    '("Reset Extraction Inline." . ("f9" . 1024))
    '("Restart." . ("62" . 338))
    '("Save." . ("5t" . 305))
    '("Save @{ident}." . ("5t" . 306))
    '("Save Corollary @{ident}." . ("5t" . 311))
    '("Save Fact @{ident}." . ("5t" . 310))
    '("Save Lemma @{ident}." . ("5t" . 308))
    '("Save Proposition @{ident}." . ("5t" . 312))
    '("Save Remark @{ident}." . ("5t" . 309))
    '("Save Theorem @{ident}." . ("5t" . 307))
    '("Scheme Equality for @{ident}." . ("bs" . 940))
    '("Scheme Induction for @{ident} Sort @{sort}." . ("bs" . 941))
    '("Scheme @{ident} := Induction for @{ident'} Sort @{sort}." . ("bs" . 938))
    '("Scheme @{ident} := Minimality for @{ident'} Sort @{sort}." . ("bs" . 939))
    '("Search @{qualid}." . ("46" . 197))
    '("Search \"@{string}\"." . ("46" . 199))
    '("Search @{term_pattern}." . ("46" . 201))
    '("Search @{search_term+}." . ("46" . 202))
    '("Search -@{search_term+}." . ("46" . 202))
    '("Search \"@{string}\"%@{key}." . ("46" . 200))
    '("@{selector}: Search @{search_term+}." . ("46" . 205))
    '("@{selector}: Search -@{search_term+}." . ("46" . 205))
    '("SearchAbout @{qualid}." . ("46" . 206))
    '("SearchHead @{term}." . ("47" . 207))
    '("@{selector}: SearchHead @{term}." . ("47" . 211))
    '("SearchHead @{term} inside @{module+}." . ("47" . 208))
    '("SearchHead @{term} outside @{module+}." . ("47" . 209))
    '("Search @{search_term+} inside @{module+}." . ("46" . 203))
    '("Search @{search_term+} outside @{module+}." . ("46" . 204))
    '("SearchPattern @{term}." . ("48" . 212))
    '("@{selector}: SearchPattern @{term}." . ("48" . 215))
    '("SearchPattern @{term} inside @{module+}." . ("48" . 213))
    '("SearchPattern @{term} outside @{module+}." . ("48" . 214))
    '("SearchRewrite @{term}." . ("49" . 216))
    '("@{selector}: SearchRewrite @{term}." . ("49" . 219))
    '("SearchRewrite @{term} inside @{module+}." . ("49" . 217))
    '("SearchRewrite @{term} outside @{module+}." . ("49" . 218))
    '("Section @{ident}." . ("1f" . 70))
    '("Separate Extraction @{qualid+}." . ("f6" . 1014))
    '("Set @{flag}." . ("3s" . 170))
    '("Set @{option} @{value}." . ("3v" . 177))
    '("Set Automatic Introduction." . ("6e" . 362))
    '("Set Boolean Equality Schemes." . ("bt" . 947))
    '("Set Case Analysis Schemes." . ("bt" . 946))
    '("Set Contextual Implicit." . ("1t" . 87))
    '("Set Decidable Equality Schemes." . ("bt" . 948))
    '("Set Default Goal Selector \"@{selector}\"." . ("6k" . 366))
    '("Set Default Goal Selector." . ("6l" . 367))
    '("Set Default Proof Using \"@{expression}\"." . ("5w" . 327))
    '("Set Default Timeout @{int}." . ("54" . 276))
    '("Set Default Timeout." . ("55" . 277))
    '("Set Elimination Schemes." . ("bt" . 942))
    '("Set Extraction AutoInline." . ("f9" . 1021))
    '("Set Extraction Conservative Types." . ("f9" . 1019))
    '("Set Extraction KeepSingleton." . ("f9" . 1020))
    '("Set Extraction Optimize." . ("f9" . 1018))
    '("Set Extraction SafeImplicits." . ("fa" . 1026))
    '("Set Firstorder Depth @{n}." . ("8o" . 778))
    '("Set Firstorder Solver @{tactic}." . ("8o" . 772))
    '("Set Hide Obligations." . ("fo" . 1052))
    '("Set Hyps Limit @{num}." . ("6c" . 360))
    '("Set Hyps Limit." . ("6d" . 361))
    '("Set Implicit Arguments." . ("1r" . 81))
    '("Set Info Level @{num}." . ("9x" . 889))
    '("Set Loose Hint Behavior \"Lax\"." . ("8i" . 760))
    '("Set Loose Hint Behavior \"Strict\"." . ("8i" . 762))
    '("Set Loose Hint Behavior \"Warn\"." . ("8i" . 761))
    '("Set Ltac Debug." . ("9y" . 891))
    '("Set Maximal Implicit Insertion." . ("1v" . 91))
    '("Set Nonrecursive Elimination Schemes." . ("bt" . 944))
    '("Set Parsing Explicit." . ("21" . 99))
    '("Set Primitive Projections." . ("17" . 44))
    '("Set Printing All." . ("26" . 114))
    '("Set Printing Coercions." . ("dq" . 979))
    '("Set Printing Depth @{integer}." . ("5f" . 286))
    '("Set Printing Depth." . ("5g" . 287))
    '("Set Printing Existential Instances." . ("29" . 120))
    '("Set Printing Implicit." . ("1z" . 95))
    '("Set Printing Implicit Defensive." . ("1z" . 97))
    '("Set Printing Matching." . ("1c" . 47))
    '("Set Printing Notations." . ("bb" . 900))
    '("Set Printing Primitive Projection Compatibility." . ("17" . 46))
    '("Set Printing Primitive Projection Parameters." . ("17" . 45))
    '("Set Printing Projections." . ("16" . 42))
    '("Set Printing Records." . ("16" . 39))
    '("Set Printing Synth." . ("1c" . 53))
    '("Set Printing Universes." . ("27" . 116))
    '("Set Printing Width @{integer}." . ("5c" . 283))
    '("Set Printing Width." . ("5d" . 284))
    '("Set Printing Wildcard." . ("1c" . 50))
    '("Set Refine Instance Mode." . ("eg" . 996))
    '("Set Regular Subst Tactic." . ("7u" . 650))
    '("Set Reversible Pattern Implicit." . ("1u" . 89))
    '("Set Search Output Name Only." . ("5a" . 281))
    '("Set Shrink Abstract." . ("9s" . 884))
    '("Set Shrink Obligations." . ("fo" . 1053))
    '("Set Silent." . ("58" . 279))
    '("Set Strict Implicit." . ("1s" . 83))
    '("Set Strict Universe Declaration." . ("h8" . 1101))
    '("Set Strongly Strict Implicit." . ("1s" . 85))
    '("Set Suggest Proof Using." . ("5w" . 328))
    '("Set Tactic Compat Context." . ("9s" . 869))
    '("Set Transparent Obligations." . ("fo" . 1051))
    '("Set Universal Lemma Under Conjunction." . ("6s" . 390))
    '("Show." . ("69" . 349))
    '("Show @{num}." . ("69" . 350))
    '("Show Conjectures." . ("69" . 355))
    '("Show Existentials." . ("69" . 358))
    '("Show Intro." . ("69" . 356))
    '("Show Intros." . ("69" . 357))
    '("Show Obligation Tactic." . ("fo" . 1043))
    '("Show Proof." . ("69" . 354))
    '("Show Script." . ("69" . 353))
    '("Solve All Obligations." . ("fo" . 1048))
    '("Solve All Obligations with @{expr}." . ("fo" . 1048))
    '("Solve Obligations." . ("fo" . 1047))
    '("Solve Obligations of @{ident}." . ("fo" . 1047))
    '("Solve Obligations of @{ident} with @{expr}." . ("fo" . 1047))
    '("Solve Obligations with @{expr}." . ("fo" . 1047))
    '("Strategy @{level} [@{qualid+}]." . ("5l" . 294))
    '("SubClass @{ident} := @{type}." . ("dj" . 973))
    '("Tactic Notation @{tactic_level} := @{tactic}." . ("bo" . 936))
    '("Tactic Notation @{tactic_level} @{prod_item+} := @{tactic}." . ("bo" . 936))
    '("Test @{flag}." . ("3u" . 176))
    '("Test @{option}." . ("3x" . 183))
    '("Test Automatic Introduction." . ("6e" . 362))
    '("Test Boolean Equality Schemes." . ("bt" . 947))
    '("Test Case Analysis Schemes." . ("bt" . 946))
    '("Test Contextual Implicit." . ("1t" . 87))
    '("Test Decidable Equality Schemes." . ("bt" . 948))
    '("Test Default Goal Selector." . ("6l" . 367))
    '("Test Default Timeout." . ("55" . 277))
    '("Test Elimination Schemes." . ("bt" . 942))
    '("Test Extraction AutoInline." . ("f9" . 1021))
    '("Test Extraction Conservative Types." . ("f9" . 1019))
    '("Test Extraction KeepSingleton." . ("f9" . 1020))
    '("Test Extraction Optimize." . ("f9" . 1018))
    '("Test Extraction SafeImplicits." . ("fa" . 1026))
    '("Test Hide Obligations." . ("fo" . 1052))
    '("Test Hyps Limit." . ("6d" . 361))
    '("Test Implicit Arguments." . ("1r" . 81))
    '("Test Ltac Debug." . ("9y" . 891))
    '("Test Maximal Implicit Insertion." . ("1v" . 91))
    '("Test Nonrecursive Elimination Schemes." . ("bt" . 944))
    '("Test Parsing Explicit." . ("21" . 99))
    '("Test Primitive Projections." . ("17" . 44))
    '("Test Printing All." . ("26" . 114))
    '("Test Printing Coercions." . ("dq" . 979))
    '("Test Printing Depth." . ("5g" . 287))
    '("Test Printing Existential Instances." . ("29" . 120))
    '("Test Printing If for @{ident}." . ("1c" . 62))
    '("Test Printing Implicit." . ("1z" . 95))
    '("Test Printing Implicit Defensive." . ("1z" . 97))
    '("Test Printing Let for @{ident}." . ("1c" . 58))
    '("Test Printing Matching." . ("1c" . 47))
    '("Test Printing Notations." . ("bb" . 900))
    '("Test Printing Primitive Projection Compatibility." . ("17" . 46))
    '("Test Printing Primitive Projection Parameters." . ("17" . 45))
    '("Test Printing Projections." . ("16" . 42))
    '("Test Printing Records." . ("16" . 39))
    '("Test Printing Synth." . ("1c" . 53))
    '("Test Printing Universes." . ("27" . 116))
    '("Test Printing Width." . ("5d" . 284))
    '("Test Printing Wildcard." . ("1c" . 50))
    '("Test Refine Instance Mode." . ("eg" . 996))
    '("Test Regular Subst Tactic." . ("7u" . 650))
    '("Test Reversible Pattern Implicit." . ("1u" . 89))
    '("Test Search Output Name Only." . ("5a" . 281))
    '("Test Shrink Abstract." . ("9s" . 884))
    '("Test Shrink Obligations." . ("fo" . 1053))
    '("Test Silent." . ("58" . 279))
    '("Test Strict Implicit." . ("1s" . 83))
    '("Test Strict Universe Declaration." . ("h8" . 1101))
    '("Test Strongly Strict Implicit." . ("1s" . 85))
    '("Test Suggest Proof Using." . ("5w" . 328))
    '("Test Tactic Compat Context." . ("9s" . 869))
    '("Test Transparent Obligations." . ("fo" . 1051))
    '("Test Universal Lemma Under Conjunction." . ("6s" . 390))
    '("Theorem @{ident} : @{type}." . ("14" . 26))
    '("Theorem @{ident} @{binders} : @{type}." . ("14" . 26))
    '("Time @{command}." . ("51" . 273))
    '("Timeout @{int} @{command}." . ("53" . 275))
    '("Transparent @{qualid+}." . ("5k" . 292))
    '("Typeclasses eauto :=." . ("ef" . 995))
    '("Typeclasses eauto := debug." . ("ef" . 995))
    '("Typeclasses Opaque @{ident+}." . ("ee" . 994))
    '("Typeclasses Transparent @{ident+}." . ("ee" . 993))
    '("Undelimit Scope @{scope}." . ("bj" . 910))
    '("Undo." . ("61" . 336))
    '("Undo @{num}." . ("61" . 337))
    '("Unfocus." . ("64" . 342))
    '("Unfocused." . ("65" . 343))
    '("Universe @{ident}." . ("h5" . 1097))
    '("Unset @{flag}." . ("3t" . 173))
    '("Unset @{option}." . ("3w" . 180))
    '("Unset Automatic Introduction." . ("6e" . 362))
    '("Unset Boolean Equality Schemes." . ("bt" . 947))
    '("Unset Case Analysis Schemes." . ("bt" . 946))
    '("Unset Contextual Implicit." . ("1t" . 87))
    '("Unset Decidable Equality Schemes." . ("bt" . 948))
    '("Unset Default Goal Selector." . ("6l" . 367))
    '("Unset Default Timeout." . ("55" . 277))
    '("Unset Elimination Schemes." . ("bt" . 942))
    '("Unset Extraction AutoInline." . ("f9" . 1021))
    '("Unset Extraction Conservative Types." . ("f9" . 1019))
    '("Unset Extraction KeepSingleton." . ("f9" . 1020))
    '("Unset Extraction Optimize." . ("f9" . 1018))
    '("Unset Extraction SafeImplicits." . ("fa" . 1026))
    '("Unset Hide Obligations." . ("fo" . 1052))
    '("Unset Hyps Limit." . ("6d" . 361))
    '("Unset Implicit Arguments." . ("1r" . 81))
    '("Unset Info Level @{num}." . ("9x" . 890))
    '("Unset Ltac Debug." . ("9y" . 891))
    '("Unset Maximal Implicit Insertion." . ("1v" . 91))
    '("Unset Nonrecursive Elimination Schemes." . ("bt" . 944))
    '("Unset Parsing Explicit." . ("21" . 99))
    '("Unset Primitive Projections." . ("17" . 44))
    '("Unset Printing All." . ("26" . 114))
    '("Unset Printing Coercions." . ("dq" . 979))
    '("Unset Printing Depth." . ("5g" . 287))
    '("Unset Printing Existential Instances." . ("29" . 120))
    '("Unset Printing Implicit." . ("1z" . 95))
    '("Unset Printing Implicit Defensive." . ("1z" . 97))
    '("Unset Printing Matching." . ("1c" . 47))
    '("Unset Printing Notations." . ("bb" . 900))
    '("Unset Printing Primitive Projection Compatibility." . ("17" . 46))
    '("Unset Printing Primitive Projection Parameters." . ("17" . 45))
    '("Unset Printing Projections." . ("16" . 42))
    '("Unset Printing Records." . ("16" . 39))
    '("Unset Printing Synth." . ("1c" . 53))
    '("Unset Printing Universes." . ("27" . 116))
    '("Unset Printing Width." . ("5d" . 284))
    '("Unset Printing Wildcard." . ("1c" . 50))
    '("Unset Refine Instance Mode." . ("eg" . 996))
    '("Unset Regular Subst Tactic." . ("7u" . 650))
    '("Unset Reversible Pattern Implicit." . ("1u" . 89))
    '("Unset Search Output Name Only." . ("5a" . 281))
    '("Unset Shrink Abstract." . ("9s" . 884))
    '("Unset Shrink Obligations." . ("fo" . 1053))
    '("Unset Silent." . ("58" . 279))
    '("Unset Strict Implicit." . ("1s" . 83))
    '("Unset Strict Universe Declaration." . ("h8" . 1101))
    '("Unset Strongly Strict Implicit." . ("1s" . 85))
    '("Unset Suggest Proof Using." . ("5w" . 328))
    '("Unset Tactic Compat Context." . ("9s" . 869))
    '("Unset Transparent Obligations." . ("fo" . 1051))
    '("Unset Universal Lemma Under Conjunction." . ("6s" . 390))
    '("Unshelve." . ("9m" . 837))
    '("Variable @{ident} : @{term}." . ("10" . 8))
    '("Variable @{ident+} : @{term}." . ("10" . 10))
    '("Extraction @{Inline | NoInline} @{qualid+}." . ("f9" . 1022))
    '("Hint @{Transparent | Opaque} @{qualid}." . ("8d" . 744))
    '("Hint @{Transparent | Opaque} @{ident+}." . ("8d" . 745))
    '("Hint @{Transparent | Opaque} @{qualid} : @{ident+}." . ("8d" . 744))
    '("Hint @{Transparent | Opaque} @{ident+} : @{ident+}." . ("8d" . 745))
    '("Local Hint @{Transparent | Opaque} @{qualid}." . ("8d" . 744))
    '("Local Hint @{Transparent | Opaque} @{ident+}." . ("8d" . 745))
    '("Local Hint @{Transparent | Opaque} @{qualid} : @{ident+}." . ("8d" . 744))
    '("Local Hint @{Transparent | Opaque} @{ident+} : @{ident+}." . ("8d" . 745))
    '("Print Instances @{Reflexive | Symmetric | Transitive | Equivalence | PreOrder | PER | Proper}." . ("gi" . 1090))
    '("Require @{Import | Export} @{qualid+}." . ("4e" . 234))
    '("Typeclasses eauto := @{dfs | bfs} @{depth}." . ("ef" . 995))
    '("Typeclasses eauto := debug @{dfs | bfs} @{depth}." . ("ef" . 995))))

(defconst company-coq--refman-scope-abbrevs
  (list
    '("bool_scope" . ("bl" . 939))
    '("char_scope" . ("bl" . 943))
    '("core_scope" . ("bl" . 941))
    '("list_scope" . ("bl" . 940))
    '("nat_scope" . ("bl" . 932))
    '("N_scope" . ("bl" . 933))
    '("positive_scope" . ("bl" . 935))
    '("Qc_scope" . ("bl" . 937))
    '("Q_scope" . ("bl" . 936))
    '("real_scope" . ("bl" . 938))
    '("string_scope" . ("bl" . 942))
    '("type_scope" . ("bl" . 931))
    '("Z_scope" . ("bl" . 934))))

(defconst company-coq--refman-error-abbrevs
  (list
    '("@{ident} already exists" . ("10" . 3))
    '("@{ident} cannot be defined." . ("16" . 36))
    '("@{ident} is already used" . ("6w" . 425))
    '("@{ident} is not a local definition" . ("6z" . 450))
    '("@{ident} is used in conclusion" . ("76" . 505))
    '("@{ident} is used in hypothesis @{ident'}" . ("76" . 504))
    '("@{ident} is used in the conclusion" . ("6z" . 446))
    '("@{ident} is used in the hypothesis @{ident'}" . ("6z" . 447))
    '("@{qualid} is not a module" . ("2c" . 166))
    '("Argument of match does not evaluate to a term" . ("9s" . 866))
    '("arguments of ring_simplify do not have all the same type" . ("fw" . 1059))
    '("Attempt to save an incomplete proof" . ("5t" . 303))
    '("bad lemma for decidability of equality" . ("fx" . 1064))
    '("Bad magic number" . ("4e" . 239))
    '("bad ring structure" . ("fx" . 1063))
    '("cannot be used as a hint" . ("8d" . 734))
    '("Cannot build functional inversion principle" . ("1d" . 69))
    '("Cannot define graph for @{ident}@{hole}" . ("1d" . 67))
    '("Cannot define principle(s) for @{ident}@{hole}" . ("1d" . 68))
    '("cannot find a declared ring structure for equality term" . ("fw" . 1061))
    '("cannot find a declared ring structure over term" . ("fw" . 1060))
    '("Cannot find induction information on @{qualid}" . ("7k" . 570))
    '("Cannot find inversion information for hypothesis @{ident}" . ("97" . 814))
    '("Cannot find library foo in loadpath" . ("4e" . 237))
    '("Cannot find the source class of @{qualid}" . ("di" . 962))
    '("Cannot handle mutually (co)inductive records." . ("16" . 38))
    '("Cannot infer a term for this placeholder" . ("1o" . 73))
    '("Cannot load @{qualid}: no physical path bound to @{dirpath}" . ("4e" . 236))
    '("Cannot move @{ident} after @{ident}: it depends on @{ident}" . ("71" . 464))
    '("Cannot move @{ident} after @{ident}: it occurs in @{ident}" . ("71" . 463))
    '("Cannot recognize @{class} as a source class of @{qualid}" . ("di" . 963))
    '("Cannot solve the goal" . ("9s" . 851))
    '("Cannot use mutual definition with well-founded recursion or measure" . ("1d" . 66))
    '("Can’t find file @{ident} on loadpath" . ("4c" . 230))
    '("Compiled library @{ident}.vo makes inconsistent assumptions over library @{qualid}" . ("4e" . 238))
    '("Condition not satisfied" . ("9s" . 880))
    '("does not denote an evaluable constant" . ("82" . 695))
    '("does not respect the uniform inheritance condition" . ("di" . 964))
    '("Failed to progress" . ("9s" . 844))
    '("File not found on loadpath : \"@{string}\"" . ("4g" . 245))
    '("Found target class @{class} instead of @{class}" . ("di" . 965))
    '("Funclass cannot be a source class" . ("di" . 959))
    '("goal does not satisfy the expected preconditions" . ("7n" . 591))
    '("Goal is solvable by congruence but some arguments are missing. Try \"congruence with @{hole}\", replacing metavariables by arbitrary terms." . ("8p" . 783))
    '("Hypothesis @{ident} must contain at least one Function" . ("97" . 813))
    '("I don’t know how to handle dependent equality" . ("8p" . 782))
    '("Impossible to unify @{hole} with @{hole}" . ("6s" . 381))
    '("In environment @{hole} the term: @{term} does not have type @{term}" . ("fl" . 1038))
    '("invalid argument" . ("6r" . 377))
    '("Invalid backtrack" . ("4w" . 267))
    '("is already a coercion" . ("di" . 958))
    '("is not a function" . ("di" . 961))
    '("is not an inductive type" . ("8d" . 740))
    '("Loading of ML object file forbidden in a native Coq" . ("4g" . 246))
    '("Module/section @{module} not found" . ("47" . 210))
    '("must be a transparent constant" . ("dj" . 971))
    '("name @{ident} is already used" . ("6w" . 428))
    '("No applicable tactic" . ("9s" . 845))
    '("No argument name @{ident}" . ("1d" . 65))
    '("No discriminable equalities" . ("7l" . 581))
    '("No evars" . ("8u" . 792))
    '("No focused proof" . ("5q" . 300))
    '("No focused proof (No proof-editing in progress)" . ("5x" . 331))
    '("No focused proof to restart" . ("62" . 339))
    '("No matching clauses for match" . ("9s" . 865))
    '("No matching clauses for match goal" . ("9s" . 870))
    '("No primitive equality found" . ("7l" . 574))
    '("No product even after head-reduction" . ("6w" . 424))
    '("No progress made" . ("gq" . 1094))
    '("No such assumption" . ("6q" . 374))
    '("No such binder" . ("6m" . 368))
    '("no such entry" . ("4v" . 264))
    '("No such goal" . ("69" . 351))
    '("No such goal. Focus next goal with bullet @{bullet}." . ("67" . 347))
    '("No such goal. Try unfocusing with \"}\"." . ("67" . 348))
    '("No such hypothesis" . ("6w" . 438))
    '("No such hypothesis in current goal" . ("6w" . 431))
    '("No such label @{ident}" . ("2c" . 144))
    '("Non exhaustive pattern-matching" . ("da" . 955))
    '("Non strictly positive occurrence of @{ident} in @{type}" . ("12" . 21))
    '("not a context variable" . ("9s" . 872))
    '("not a defined object" . ("3p" . 164))
    '("Not a discriminable equality" . ("7l" . 575))
    '("Not a primitive equality" . ("7n" . 585))
    '("Not a projectable equality but a discriminable one" . ("7n" . 583))
    '("Not a proposition or a type" . ("76" . 486))
    '("not a valid ring equation" . ("fw" . 1058))
    '("Not a variable or hypothesis" . ("8v" . 794))
    '("Not an evar" . ("8t" . 790))
    '("Not an exact proof" . ("6p" . 371))
    '("Not an inductive goal with 1 constructor" . ("6u" . 408))
    '("Not an inductive goal with 2 constructors" . ("6u" . 414))
    '("Not an inductive product" . ("6u" . 402))
    '("Not convertible" . ("7w" . 657))
    '("not declared" . ("di" . 957))
    '("Not enough constructors" . ("6u" . 403))
    '("Not equal" . ("8r" . 785))
    '("Not reducible" . ("7z" . 678))
    '("Not the right number of induction arguments" . ("7k" . 571))
    '("Not the right number of missing arguments" . ("6m" . 369))
    '("Not unifiable" . ("8s" . 787))
    '("Nothing to do, it is an equality between convertible terms" . ("7n" . 584))
    '("Nothing to rewrite" . ("gq" . 1093))
    '("omega can’t solve this system" . ("ek" . 997))
    '("omega: Can’t solve a goal with equality on @{type}" . ("ek" . 1004))
    '("omega: Can’t solve a goal with non-linear products" . ("ek" . 1003))
    '("omega: Can’t solve a goal with proposition variables" . ("ek" . 1001))
    '("omega: Not a quantifier-free goal" . ("ek" . 998))
    '("omega: Unrecognized atomic proposition: @{prop}" . ("ek" . 1000))
    '("omega: Unrecognized predicate or connective: @{ident}" . ("ek" . 999))
    '("omega: Unrecognized proposition" . ("ek" . 1002))
    '("Proof is not complete" . ("76" . 489))
    '("quote: not a simple fixpoint" . ("98" . 818))
    '("Records declared with the keyword Record or Structure cannot be recursive." . ("16" . 37))
    '("Require is not allowed inside a module or a module type" . ("4e" . 241))
    '("ring @{operation} should be declared as a morphism" . ("fx" . 1065))
    '("Signature components for label @{ident} do not match" . ("2c" . 145))
    '("Sortclass cannot be a source class" . ("di" . 960))
    '("Statement without assumptions" . ("6t" . 392))
    '("Tactic Failure @{message} (level @{n})" . ("9s" . 861))
    '("Tactic generated a subgoal identical to the original goal" . ("7s" . 627))
    '("terms do not have convertible types" . ("7t" . 636))
    '("The @{num}th argument of @{ident} must be @{ident'} in @{type}" . ("12" . 23))
    '("The conclusion is not a substitutive equation" . ("8y" . 797))
    '("The conclusion of @{type} is not valid; it must be built from @{ident}" . ("12" . 22))
    '("The file @{ident}.vo contains library @{dirpath} and not library @{dirpath'}" . ("4e" . 240))
    '("The recursive argument must be specified" . ("1d" . 64))
    '("The reference @{qualid} was not found in the current environment" . ("46" . 198))
    '("The term @{form} has type @{hole} which should be Set, Prop or Type" . ("14" . 27))
    '("The term @{term} has type @{type} while it is expected to have type @{type}" . ("11" . 17))
    '("The term provided does not end with an equation" . ("7s" . 626))
    '("The variable @{ident} is already defined" . ("73" . 470))
    '("This is not the last opened module" . ("2c" . 146))
    '("This is not the last opened module type" . ("2c" . 158))
    '("This is not the last opened section" . ("1g" . 72))
    '("This proof is focused, but cannot be unfocused this way" . ("66" . 344))
    '("This tactic has more than one success" . ("9s" . 849))
    '("Unable to apply" . ("6t" . 393))
    '("Unable to find an instance for the variables @{ident+}" . ("6s" . 382))
    '("Unable to satisfy the rewriting constraints" . ("gq" . 1095))
    '("Undeclared universe @{ident}" . ("h6" . 1099))
    '("Universe inconsistency" . ("35" . 162))
    '("Variable @{ident} is already declared" . ("76" . 493))
    '("Wrong bullet @{bullet}1 : Bullet @{bullet}2 is mandatory here." . ("67" . 346))
    '("Wrong bullet @{bullet}1 : Current bullet @{bullet}2 is not finished." . ("67" . 345))))

(provide 'company-coq-abbrev)
;;; company-coq-abbrev.el ends here
